### ISSUE TITLE
GELI > ZFS Encryption Conversion

### ISSUE THREAD

**Issue by distancesprinter** [freenas/documentation#288]
The GELI conversion procedure does not work.

cannot receive incremental stream: encryption property 'encryption' cannot be set for incremental streams.

**Comment by Mrt134** [comment]
Thanks for letting us know - is this on a 12.0-BETA2 system?

**Comment by distancesprinter** [comment]
TrueNAS-12.0-BETA2.1

**Comment by Mrt134** [comment]
Perfect, thanks! We'll queue up another run-through of the instructions and see what needs to be updated.

**Comment by q5sys** [comment]
> The GELI conversion procedure does not work.
> 
> cannot receive incremental stream: encryption property 'encryption' cannot be set for incremental streams.

You have to do this one dataset/snapshot at a time.
We are working on trying to make this easier but until that is finished here is an updated example:

Legend:
```
GELI Pool = pool_a
Origin Dataset = dataset_1
Latest Snapshot of GELI Pool = snapshot_name
ZFS Native Encrypted Pool = pool_b
Receieving Dataset = dataset_2
```

1. Create a new encrypted pool in **Storage > Pools**, as described at the [beginning of this article](#encrypting-a-storage-pool).
2. Open the **Shell**. Make a new snapshot of the GELI pool and dataset with the data to be migrated: `zfs snapshot -r pool_a/dataset_1@snapshot_name`.
3. Create a passphrase: `echo passphrase > /tmp/pass`.
4. Use ZFS send/receive to transfer the data between pools: `zfs send -Rv pool_a/dataset_1@snapshot_name | zfs recv -o encryption=on -o keyformat=passphrase -o keylocation=file:///tmp/pass pool_b/dataset_2`.
5. When the transfer is complete, go to **Storage > Pools** and lock the new dataset. After locking the dataset, immediately unlock it. TrueNAS prompts for the passphrase. After entering the passphrase and the pool is unlocked, you can delete the `/tmp/pass` file used for the transfer.
6. If desired, you can convert the dataset to use a keyfile instead of a passphrase. To use a passphrase instead of a keyfile, open the dataset <i class="fas fa-ellipsis-v" aria-hidden="true" title="Options"></i> (Options) and click **Encryption Options**. Change the *Encryption Type* from **Passphrase** to **Key** and save. Remember to back up your keyfile immediately!
7. Repeat this process for every dataset in the Pool that needs to be migrated.

**Comment by q5sys** [comment]
We're tracking this issue here: https://jira.ixsystems.com/browse/DOCS-942
